services:
  dev-database:
    container_name: platform-database
    image: postgres:18
    ports:
      - '$DATABASE_PORT:$DATABASE_PORT'
    environment:
      - PGPORT=$DATABASE_PORT
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
