import { zodResolver } from '@hookform/resolvers/zod';
import { type ReactNode, useEffect, useMemo, useState } from 'react';
import { Controller, useForm, useWatch } from 'react-hook-form';
import { toast } from 'sonner';
import {
  type ClinicReportCreateRequest,
  ClinicReportCreateRequestSchema,
  type ClinicResponse,
  type PatientResponse,
  REFERENCE_ITEMS_LIMIT,
} from 'platform/common-base';
import { UserRole } from 'platform/prisma';
import { api } from '../../api/client.api';
import { useRequest } from '../../hooks/request.hook';
import { useAuthenticatedUser } from '../../providers/auth.provider';
import { formatOptionLabel } from '../../utils/formatting.utils';
import { getErrorMessage } from '../../utils/request.utils';
import { EntityAutocomplete } from '../form/entity-autocomplete.component';
import { Button } from '../shadcn/ui/button';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '../shadcn/ui/dialog';
import { Field, FieldError, FieldLabel } from '../shadcn/ui/field';
import { Spinner } from '../shadcn/ui/spinner';

export const ClinicReportModal = ({
  trigger,
  onSaved,
}: {
  trigger: ReactNode;
  onSaved: () => void;
}) => {
  const [open, setOpen] = useState(false);
  const user = useAuthenticatedUser();
  const form = useForm<ClinicReportCreateRequest>({
    resolver: zodResolver(ClinicReportCreateRequestSchema),
    defaultValues: { clinicId: 0, patientId: 0 },
  });
  const clinicId = useWatch({ control: form.control, name: 'clinicId' });
  const referencesRequest = useRequest(async () => {
    const [clinics, patients] = await Promise.all([
      api.clinic.findMany({
        where: user.role === UserRole.Admin ? {} : { managerId: user.id },
        orderBy: { name: 'asc' },
        take: REFERENCE_ITEMS_LIMIT,
      }),
      api.patient.findMany({
        where:
          user.role === UserRole.Admin
            ? {}
            : { clinic: { managerId: user.id } },
        orderBy: { userId: 'asc' },
        take: REFERENCE_ITEMS_LIMIT,
      }),
    ]);
    return { clinics: clinics.items, patients: patients.items };
  });
  const createRequest = useRequest(api.clinicReport.create, {
    onSuccess: () => {
      toast.success('Clinic report created.');
      setOpen(false);
      onSaved();
    },
    onError: (error) => toast.error(getErrorMessage(error)),
  });
  const patients = useMemo(
    () =>
      (referencesRequest.data?.patients ?? []).filter(
        (patient) => patient.clinicId === clinicId,
      ),
    [clinicId, referencesRequest.data?.patients],
  );

  useEffect(() => {
    if (open) {
      form.reset({ clinicId: 0, patientId: 0 });
      void referencesRequest.fetch().catch(() => undefined);
    }
  }, [form, open, referencesRequest.fetch]);

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>{trigger}</DialogTrigger>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>Create clinic report</DialogTitle>
          <DialogDescription>
            {user.role === UserRole.Admin
              ? 'Select a patient from any clinic. Report content is generated by the server.'
              : 'Select a patient from one of your clinics. Report content is generated by the server.'}
          </DialogDescription>
        </DialogHeader>
        <form
          noValidate
          className="grid gap-4"
          onSubmit={form.handleSubmit(
            (data) => void createRequest.fetch(data).catch(() => undefined),
          )}
        >
          <Field data-invalid={Boolean(form.formState.errors.clinicId)}>
            <FieldLabel htmlFor="clinic-report-clinic">Clinic</FieldLabel>
            <Controller
              control={form.control}
              name="clinicId"
              render={({ field }) => (
                <EntityAutocomplete
                  id="clinic-report-clinic"
                  value={(referencesRequest.data?.clinics ?? []).find(
                    (clinic) => clinic.id === field.value,
                  )}
                  items={referencesRequest.data?.clinics ?? []}
                  placeholder="Search for a clinic…"
                  emptyLabel="No clinics found."
                  loading={referencesRequest.isLoading}
                  invalid={Boolean(form.formState.errors.clinicId)}
                  getKey={(clinic: ClinicResponse) => String(clinic.id)}
                  getLabel={(clinic: ClinicResponse) => clinic.name}
                  onChange={(clinic) => {
                    field.onChange(clinic?.id ?? 0);
                    form.setValue('patientId', 0);
                  }}
                />
              )}
            />
            <FieldError errors={[form.formState.errors.clinicId]} />
          </Field>
          <Field data-invalid={Boolean(form.formState.errors.patientId)}>
            <FieldLabel htmlFor="clinic-report-patient">Patient</FieldLabel>
            <Controller
              control={form.control}
              name="patientId"
              render={({ field }) => (
                <EntityAutocomplete
                  id="clinic-report-patient"
                  value={patients.find(
                    (patient) => patient.userId === field.value,
                  )}
                  items={patients}
                  placeholder={
                    clinicId ? 'Search for a patient…' : 'Select a clinic first'
                  }
                  emptyLabel="No patients found for this clinic."
                  loading={referencesRequest.isLoading}
                  disabled={!clinicId}
                  invalid={Boolean(form.formState.errors.patientId)}
                  getKey={(patient: PatientResponse) => String(patient.userId)}
                  getLabel={(patient: PatientResponse) =>
                    formatOptionLabel(patient.user.fullName, patient.user.email)
                  }
                  onChange={(patient) => field.onChange(patient?.userId ?? 0)}
                />
              )}
            />
            <FieldError errors={[form.formState.errors.patientId]} />
          </Field>
          <DialogFooter>
            <Button
              type="button"
              variant="outline"
              onClick={() => setOpen(false)}
            >
              Cancel
            </Button>
            <Button type="submit" disabled={createRequest.isLoading}>
              {createRequest.isLoading && <Spinner data-icon="inline-start" />}
              Create report
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
};
