import { zodResolver } from '@hookform/resolvers/zod';
import { type ReactNode, useCallback, useEffect } from 'react';
import { Controller, useForm, useWatch } from 'react-hook-form';
import { toast } from 'sonner';
import { useDebouncedCallback } from 'use-debounce';
import {
  type ClinicReportCreateRequest,
  ClinicReportCreateRequestSchema,
  type ClinicResponse,
  type PatientResponse,
  isWho,
} from 'platform/common-base';
import { api } from '../../api/client.api';
import { SEARCH_DEBOUNCE_DELAY_MS } from '../../constants';
import { useRequest } from '../../hooks/request.hook';
import { useAuthenticatedUser } from '../../providers/auth.provider';
import { formatOptionLabel } from '../../utils/formatting.utils';
import {
  loadClinics,
  loadPatientsByClinic,
} from '../../utils/reference-loaders.utils';
import { getErrorMessage } from '../../utils/request.utils';
import { EntityAutocomplete } from '../form/entity-autocomplete.component';
import {
  FormDialog,
  useDialogReset,
  useFormDialog,
} from '../form/form-dialog.component';
import { Field, FieldError, FieldLabel } from '../shadcn/ui/field';

export const ClinicReportModal = ({
  trigger,
  onSaved,
}: {
  trigger: ReactNode;
  onSaved: () => void;
}) => {
  const user = useAuthenticatedUser();
  const { open, setOpen, closeAndSave } = useFormDialog({ onSaved });
  const form = useForm<ClinicReportCreateRequest>({
    resolver: zodResolver(ClinicReportCreateRequestSchema),
    defaultValues: { clinicId: 0, patientId: 0 },
  });
  const clinicId = useWatch({ control: form.control, name: 'clinicId' });
  const clinicsRequest = useRequest(() => loadClinics(user));
  const patientsRequest = useRequest((id: number, search?: string) =>
    loadPatientsByClinic(user, id, search ?? ''),
  );

  const createRequest = useRequest(api.clinicReport.create, {
    onSuccess: () => {
      toast.success('Clinic report created.');
      closeAndSave();
    },
    onError: (error) => toast.error(getErrorMessage(error)),
  });

  const loadPatients = useCallback(
    (search = '') => {
      if (clinicId) {
        void patientsRequest.fetch(clinicId, search);
      }
    },
    [clinicId, patientsRequest.fetch],
  );

  const searchPatients = useDebouncedCallback((search: string) => {
    loadPatients(search.trim());
  }, SEARCH_DEBOUNCE_DELAY_MS);

  useEffect(() => {
    loadPatients();
  }, [loadPatients]);

  useDialogReset({
    open,
    reset: form.reset,
    getResetValues: () => ({ clinicId: 0, patientId: 0 }),
    onOpen: () => {
      void clinicsRequest.fetch();
    },
  });

  return (
    <FormDialog
      trigger={trigger}
      title="Create clinic report"
      description={
        isWho(user.role).isAdmin
          ? 'Select a patient from any clinic. Report content is generated by the server.'
          : 'Select a patient from one of your clinics. Report content is generated by the server.'
      }
      submitLabel="Create report"
      loading={createRequest.isLoading}
      open={open}
      onOpenChange={setOpen}
      form={form}
      onSubmit={(data) => void createRequest.fetch(data)}
    >
      <Field data-invalid={Boolean(form.formState.errors.clinicId)}>
        <FieldLabel htmlFor="clinic-report-clinic">Clinic</FieldLabel>
        <Controller
          control={form.control}
          name="clinicId"
          render={({ field }) => (
            <EntityAutocomplete
              id="clinic-report-clinic"
              value={(clinicsRequest.data ?? []).find(
                (clinic) => clinic.id === field.value,
              )}
              items={clinicsRequest.data ?? []}
              placeholder="Search for a clinic…"
              emptyLabel="No clinics found."
              loading={clinicsRequest.isLoading}
              invalid={Boolean(form.formState.errors.clinicId)}
              getKey={(clinic: ClinicResponse) => String(clinic.id)}
              getLabel={(clinic: ClinicResponse) => clinic.name}
              onChange={(clinic) => {
                field.onChange(clinic?.id ?? 0);
                form.setValue('patientId', 0);
              }}
            />
          )}
        />
        <FieldError errors={[form.formState.errors.clinicId]} />
      </Field>
      <Field data-invalid={Boolean(form.formState.errors.patientId)}>
        <FieldLabel htmlFor="clinic-report-patient">Patient</FieldLabel>
        <Controller
          control={form.control}
          name="patientId"
          render={({ field }) => (
            <EntityAutocomplete
              id="clinic-report-patient"
              value={(patientsRequest.data ?? []).find(
                (patient) => patient.userId === field.value,
              )}
              items={patientsRequest.data ?? []}
              placeholder={
                clinicId ? 'Search for a patient…' : 'Select a clinic first'
              }
              emptyLabel="No patients found for this clinic."
              loading={patientsRequest.isLoading}
              disabled={!clinicId}
              invalid={Boolean(form.formState.errors.patientId)}
              externalFiltering
              getKey={(patient: PatientResponse) => String(patient.userId)}
              getLabel={(patient: PatientResponse) =>
                formatOptionLabel(patient.user.fullName, patient.user.email)
              }
              onSearchChange={searchPatients}
              onChange={(patient) => field.onChange(patient?.userId ?? 0)}
            />
          )}
        />
        <FieldError errors={[form.formState.errors.patientId]} />
      </Field>
    </FormDialog>
  );
};
