import { zodResolver } from '@hookform/resolvers/zod';
import {
  type ClinicReportCreateRequest,
  ClinicReportCreateRequestSchema,
  type ClinicResponse,
  type PatientResponse,
} from 'platform/common-base';
import { UserRole } from 'platform/prisma';
import { type ReactNode, useEffect, useMemo, useState } from 'react';
import { Controller, useForm, useWatch } from 'react-hook-form';
import { toast } from 'sonner';
import { api } from '../../api/client.api';
import { useRequest } from '../../hooks/request.hook';
import { useAuthenticatedUser } from '../../providers/auth.provider';
import { formatOptionLabel } from '../../utils/formatting.utils';
import { getErrorMessage } from '../../utils/request.utils';
import { FormFieldGroup } from '../form/form-field-group.component';
import { SubmitLabel } from '../form/submit-label.component';
import { Button } from '../shadcn/ui/button';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '../shadcn/ui/dialog';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '../shadcn/ui/select';

export const ClinicReportModal = ({
  trigger,
  onSaved,
}: {
  trigger: ReactNode;
  onSaved: () => void;
}) => {
  const [open, setOpen] = useState(false);
  const user = useAuthenticatedUser();
  const form = useForm<ClinicReportCreateRequest>({
    resolver: zodResolver(ClinicReportCreateRequestSchema),
    defaultValues: { clinicId: 0, patientId: 0 },
  });
  const clinicId = useWatch({ control: form.control, name: 'clinicId' });
  const referencesRequest = useRequest(async () => {
    const [clinics, patients] = await Promise.all([
      api.clinic.findMany({
        where: user.role === UserRole.Admin ? {} : { managerId: user.id },
        orderBy: { name: 'asc' },
        take: 100,
      }),
      api.patient.findMany({
        where:
          user.role === UserRole.Admin
            ? {}
            : { clinic: { managerId: user.id } },
        orderBy: { userId: 'asc' },
        take: 250,
      }),
    ]);
    return { clinics: clinics.items, patients: patients.items };
  });
  const createRequest = useRequest(api.clinicReport.create, {
    onSuccess: () => {
      toast.success('Clinic report created.');
      setOpen(false);
      onSaved();
    },
    onError: (error) => toast.error(getErrorMessage(error)),
  });
  const patients = useMemo(
    () =>
      (referencesRequest.data?.patients ?? []).filter(
        (patient) => patient.clinicId === clinicId,
      ),
    [clinicId, referencesRequest.data?.patients],
  );

  useEffect(() => {
    if (open) {
      form.reset({ clinicId: 0, patientId: 0 });
      void referencesRequest.fetch().catch(() => undefined);
    }
  }, [form, open, referencesRequest.fetch]);

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>{trigger}</DialogTrigger>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>Create clinic report</DialogTitle>
          <DialogDescription>
            Select a patient from one of your clinics. Report content is
            generated by the server.
          </DialogDescription>
        </DialogHeader>
        <form
          className="grid gap-4"
          onSubmit={form.handleSubmit(
            (data) => void createRequest.fetch(data).catch(() => undefined),
          )}
        >
          <FormFieldGroup
            label="Clinic"
            htmlFor="clinic-report-clinic"
            error={form.formState.errors.clinicId?.message}
          >
            <Controller
              control={form.control}
              name="clinicId"
              render={({ field }) => (
                <Select
                  value={field.value ? String(field.value) : ''}
                  onValueChange={(value) => {
                    field.onChange(Number(value));
                    form.setValue('patientId', 0);
                  }}
                >
                  <SelectTrigger id="clinic-report-clinic" className="w-full">
                    <SelectValue placeholder="Select clinic" />
                  </SelectTrigger>
                  <SelectContent>
                    {(referencesRequest.data?.clinics ?? []).map(
                      (clinic: ClinicResponse) => (
                        <SelectItem key={clinic.id} value={String(clinic.id)}>
                          {clinic.name}
                        </SelectItem>
                      ),
                    )}
                  </SelectContent>
                </Select>
              )}
            />
          </FormFieldGroup>
          <FormFieldGroup
            label="Patient"
            htmlFor="clinic-report-patient"
            error={form.formState.errors.patientId?.message}
          >
            <Controller
              control={form.control}
              name="patientId"
              render={({ field }) => (
                <Select
                  value={field.value ? String(field.value) : ''}
                  disabled={!clinicId}
                  onValueChange={(value) => field.onChange(Number(value))}
                >
                  <SelectTrigger id="clinic-report-patient" className="w-full">
                    <SelectValue placeholder="Select patient" />
                  </SelectTrigger>
                  <SelectContent>
                    {patients.map((patient: PatientResponse) => (
                      <SelectItem
                        key={patient.userId}
                        value={String(patient.userId)}
                      >
                        {formatOptionLabel(
                          patient.user.fullName,
                          patient.user.email,
                        )}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              )}
            />
          </FormFieldGroup>
          <DialogFooter>
            <Button
              type="button"
              variant="outline"
              onClick={() => setOpen(false)}
            >
              Cancel
            </Button>
            <Button type="submit" disabled={createRequest.isLoading}>
              <SubmitLabel loading={createRequest.isLoading}>
                Create report
              </SubmitLabel>
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
};
